//printfn "Day1: Part1: %d" (Day1.solvePart1())
//printfn "Day1: Part2: %d" (Day1.solvePart2())
//printfn "Day2: Part1: %d" (Day2.solvePart1())
//printfn "Day2: Part2: %d" (Day2.solvePart2())
//printfn "Day3: Part1: %d" (Day3.solvePart1())
Day3.solvePart1()